### ISSUE TITLE
Too much caching and no such one is useful

### ISSUE THREAD

**Issue by Bread-NiceCat** [architectury/architectury-loom#202]
![MT7TVZ_82IWA5 X9}8E05NB](https://github.com/architectury/architectury-loom/assets/121159360/4fd88522-1667-4310-8945-e1c35cba5287)
Maybe the loom will auto delete older cache and auto select the latest one ?

**Comment by emyfops** [comment]
I second this
I don't know if it's because of frequent branch switching, but when I generate the sources and then switch branch, the sources are gone

**Comment by Bread-NiceCat** [comment]
maybe caused by AccessWidener?

**Comment by Bread-NiceCat** [comment]
hello ping?

**Comment by Juuxel** [comment]
Yes, AWs affect this. Each unique Minecraft jar you use in a project will get a different cache location, so if you modify an AW often, you'll get a lot of cached jars. This is how (Fabric) Loom's project-specific Minecraft jar cache works in general and it's something that is better fixed/changed upstream than in Arch Loom.

**Comment by Avanatiker** [comment]
;-; cant this be solved with excluding them from indexing?

**Comment by Juuxel** [comment]
If you mean IDEA's indexing, it already only includes the jars that are in use.

You can delete the rest manually if you need to clean the cache. (Note that it's already been optimised a bit so that it doesn't store the exact same jar multiple times.) I think something based on the last modified date could also be added on Fabric's side, but it's not something we'll modify in Arch directly.
